# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SeriesQuizz' do
pod 'MBProgressHUD', '~> 0.9'
pod 'AFNetworking', '~> 2.5'

end

target 'SeriesQuizzTests' do

end

